<p style="align: center;">
    <img align=center src="../img/dls_logo.jpg" width=500 height=500>
</p>

<h1 style="text-align: center;">
    <b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b>
</h1>

---

In [1]:
import numpy as np
import random
import scipy.stats as sps

---

## Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами - без использования пакета `NumPy` и с его использованием.

In [28]:
# для генерации матриц используем модуль np.random - он используется для генерации случайных объектов
# функция sample создает случайную выборку, в качестве аргумента ей передается кортеж (i,j)
# здесь i - число строк, j - число столбцов
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim
# используйте функцию shape, что она вывела?
print(a.shape, b.shape)
print()
print(a)
print()
print(b)

(100, 100) (100, 100)

[[0.32022309 0.35112709 0.35463295 ... 0.78622995 0.36500719 0.69922563]
 [0.59261885 0.29720909 0.65578586 ... 0.53464545 0.54560284 0.00818889]
 [0.89502971 0.65216181 0.75406621 ... 0.62208108 0.18820927 0.15965957]
 ...
 [0.64545142 0.53797647 0.97299687 ... 0.50481345 0.17926372 0.33654622]
 [0.56361145 0.38272752 0.56315273 ... 0.60924466 0.30496516 0.47500783]
 [0.31449971 0.69676373 0.64324914 ... 0.02416798 0.39818182 0.20077581]]

[[0.68983674 0.99429156 0.21872653 ... 0.64231461 0.3187248  0.79404955]
 [0.39574815 0.14880496 0.48799932 ... 0.28253038 0.35107954 0.96769114]
 [0.7545531  0.24341791 0.81353722 ... 0.32363712 0.67993732 0.77758967]
 ...
 [0.53077176 0.2450023  0.47956771 ... 0.70765452 0.63263393 0.67494388]
 [0.86260877 0.85183575 0.74035916 ... 0.32800485 0.9976979  0.95827526]
 [0.41269032 0.09814709 0.21822414 ... 0.33714418 0.17640673 0.99934799]]


In [29]:
def mult(a, b):               
    return [[sum(a[i][k] * b[k][j] for k in range(len(a[0]))) for j in range(len(b[0]))] for i in range(len(a))]

In [30]:
def np_mult(a, b):
    return a @ b

In [31]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.69 s, sys: 2.33 ms, total: 1.69 s
Wall time: 1.69 s


In [32]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.24 ms, sys: 3.18 ms, total: 5.42 ms
Wall time: 168 ms


In [33]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.7696066834105295e-11

---

## Задание 2

Вам подаются на вход два вектора `a` и `b`. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [34]:
a = np.random.sample(1000000)
b = np.random.sample(1000000)
print(a, b, sep='\n')

[0.62146162 0.64031911 0.29063025 ... 0.26955643 0.47633692 0.59791962]
[0.08968081 0.70087161 0.51588305 ... 0.69618882 0.1359142  0.7544456 ]


In [35]:
def scalar_product(a, b):
    return sum(i * j for i, j in zip(a, b))

In [36]:
def np_scalar_product(a, b):
    return np.dot(a, b)

In [37]:
%time product_1 = scalar_product(a, b)
%time product_2 = np_scalar_product(a, b)
# проверим корректность
np.abs(product_1 - product_2).sum()

CPU times: user 341 ms, sys: 1.63 ms, total: 342 ms
Wall time: 341 ms
CPU times: user 2.32 ms, sys: 67 µs, total: 2.38 ms
Wall time: 745 µs


2.2118911147117615e-09

Почему методы `NumPy` оказываются эффективнее? Что вы можете сказать о скорости вычислений в `NumPy`?

**Ответ:** cкорость вычислений векторных и матричных операций в `NumPy` сильно превосходит скорость вычислений без него, по большей части потому, что функции `NumPy` работают с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на `C/C++`, что, конечно, делает `NumPy` быстрее (функции, которые вызывает `NumPy` для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам `Python` просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

---

## Задание 3
Напишите функцию, которая находит сумму чётных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [50]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    d = a.diagonal()
    return d[d % 2 == 0].sum()

In [51]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(10000, 10000))
a

array([[7, 1, 1, ..., 5, 5, 4],
       [9, 3, 2, ..., 5, 8, 5],
       [7, 9, 6, ..., 7, 5, 9],
       ...,
       [2, 3, 4, ..., 4, 2, 5],
       [5, 2, 8, ..., 3, 3, 6],
       [1, 5, 5, ..., 8, 8, 3]])

In [52]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 3.33 ms, sys: 555 µs, total: 3.88 ms
Wall time: 3.08 ms


22116

## Задание 4
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return #YOUR CODE

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

## Задание 5

Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    #YOUR CODE

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)

## Задание 6

Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    #YOUR CODE

In [ ]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)